- name: First PlayBook
  hosts: WEB
  become: true
  tasks:
    - name: Install NIGNX web packages
      ansible.builtin.yum:
        name: nginx
        state: latest
    - name: Start NIGNX process
      ansible.builtin.systemd:
        name: nginx
        state: started
        enable: yes